spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_sector
    username: root
    password: 123456
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
server:
  port: 8801
stock:
  company-service-endpoint: http://localhost:8081
  user-service-endpoint: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
