# application.yml

spring:
  profiles:
    active: dev
  application:
    name: stockprice-svc
  datasource:
    url: ${STOCKPRICE_DATASOURCE_URL}
    username: ${STOCKPRICE_DATASOURCE_USERNAME}
    password: ${STOCKPRICE_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_ENDPOINT}
      
stock:
  company-service-endpoint: ${COMPANY_SERVICE_ENDPOINT}
  exchange-service-endpoint: ${EXCHANGE_SERVICE_ENDPOINT}
  user-service-endpoint: ${USER_SERVICE_ENDPOINT}
  sector-service-endpoint: ${SECTOR_SERVICE_ENDPOINT}
  stockprice-service-endpoint: ${STOCKPRICE_SERVICE_ENDPOINT}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT}
  gateway-service-endpoint: ${GATEWAY_SERVICE_ENDPOINT}