server:
  port: 8803
spring:
  mail:
    host: smtp.163.com
    username: liuchang3373@163.com
    password: LAEAITYCCDYUBQVG
    default-encoding: UTF-8
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: "*"