# application.yml

# application.yml

spring:
  profiles:
    active: dev
  application:
    name: email-svc
  mail:
    host: ${EMAIL_HOST}
    username: ${EMAIL_USER_NAME} 
    password: ${EAMIL_PASSWORD} 
    default-encoding: ${DEFAULT_ENCODING} 

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_ENDPOINT}
 
stock:
  company-service-endpoint: ${COMPANY_SERVICE_ENDPOINT}
  exchange-service-endpoint: ${EXCHANGE_SERVICE_ENDPOINT}
  user-service-endpoint: ${USER_SERVICE_ENDPOINT}
  sector-service-endpoint: ${SECTOR_SERVICE_ENDPOINT}
  stockprice-service-endpoint: ${STOCKPRICE_SERVICE_ENDPOINT}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT}
  gateway-service-endpoint: ${GATEWAY_SERVICE_ENDPOINT}
