spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_user
    username: root
    password: 123456
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8805
stock:
  common:
    sentry-dsn: ${SENTRY_DSN:https://80aaf4ae889b414f9fe72e3904cd5246@sentry.io/1380198}
    deploy-env: ${DEPLOY:V2}
  signing-secret: 123
  company-service-endpoint: http://localhost:8081
  user-service-endpoint: http://localhost:8080
  email-service-endpoint: http://localhost:8803
management:
  endpoints:
    web:
      exposure:
        include: "*"
