spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_user
    username: root
    password: 123456
  jpa:
    show-sql: true
  
server:
  port: 8080
stock:
  company-service-endpoint: http://localhost:8081
  user-service-endpoint: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
