spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_company
    username: root
    password: 123456
  jpa:
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
server:
  port: 8802
stock:
  company-service-endpoint: http://localhost:8081
  user-service-endpoint: http://localhost:8080
  exchange-service-endpoint: http://localhost:8800
  sector-service-endpoint: http://localhost:8801
management:
  endpoints:
    web:
      exposure:
        include: "*"
