spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_company
    username: root
    password: 123456
  jpa:
    show-sql: true
  
server:
  port: 8081
stock:
  company-service-endpoint: http://localhost:8081
  user-service-endpoint: http://localhost:8080
  exchange-service-endpoint: http://localhost:8082
  sector-service-endpoint: http://localhost:8083
management:
  endpoints:
    web:
      exposure:
        include: "*"
